location                    = "Denmark East"
resource_group_name         = "mate-azure-task-12"
storage_account_name        = "matestoragemmacc"
storage_container_name      = "task-artifacts"
virtual_network_name        = "vnet"
vnet_address_prefix         = "10.0.0.0/16"
subnet_name                 = "default"
subnet_address_prefix       = "10.0.0.0/24"
network_security_group_name = "defaultnsg"
public_ip_address_name      = "linuxboxpip"
vm_name                     = "matebox"
vm_size                     = "Standard_B1s"
ssh_key_public              = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDpozaCFc5ac++xHMugNfzwtSNWKnlA+2lVjjlhvcb/2nZJujKU3R/zN0g5HhqW2PAMHygwzvF2w5HlPjKXACt08bROK1YGiI3KHgpOnvRspDtolEFrJ9AtBg7H34Eoz3dszMhmYpWCFnC8ayPqRMxJPoYde7hUWuntaF7/o4eEK/e2U/5dknJXPaQj6Bbe7YEyRk6EjI2J/b5ACo/D5+xfBNb/KUObofDWVuSO1/rehppu+v1K0LDHCdtsXznGmcGAvHL7qLo2RTusOdkPPEGYOR725xlGzd9c10tigxnwohhMPTMPwSsEW+amb+OZQQZ0cf8JKgpV7Vjamt+Sg5jnkpzTloBGpJGo59igA5vIKd3NOrq2BXn3NMjdkTLfICcCubGnXaUudNsZZ3WuSCt8o39Up83xbwZmfsTDFJOZUTQl7FTnqJ8pP7Kyk+La+vE6F275I8sWQ8PEljlDG9aeUJAoUfEBMFZFp71d0l0d0pzAEr/sex8vKiqN45qXCUs= id245674"
dns_label                   = "matetask"