location                    = "uksouth"
resource_group_name         = "mate-azure-task-12"
virtual_network_name        = "vnet"
vnet_address_prefix         = "10.0.0.0/16"
subnet_name                 = "default"
subnet_address_prefix       = "10.0.0.0/24"
network_security_group_name = "defaultnsg"
public_ip_address_name      = "linuxboxpip"
vm_name                     = "matebox"
vm_size                     = "Standard_B1s"
dns_label                   = "matetask"
storage_account_name        = "matetaskstorage9842"
ssh_key_public              = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVbMi7hYL6D49F6xe+YLMfEhsK+gvC3+4uDU0OY40gHL5lUdNYZBEdg96jAYGY2MnNgWejLPGbwAnl/kkjFipxwvrSsMfKtlEUqdG8FPrWvphmUOMfql1tmLkDkwZhud5HCbkU66/aUzkA7ZaNBNAil07XuSvBY3S5fTRcCDIPA5H6gph0cdujdOOB8QlLc2jItS+Vk1BaKplquas8CyqQNcIVvCitoAFaiNUA45JLBUAUV7yhls2w/fObmRtdXwT+NhUWjPXnFN/7eGW0H16isMf1NR3u5s2zPN8ta6cwRcIfxp/qmDeBZ4ikXtQB6kmMEJTh6DADoOZM+LOWo/z4GuA/zF1tY+yAeJHUWgw9d9yoir3kZxI2AFkSioiqZYBpZNbeuDYyXRNUpJh46zMNraIK84C1YWzPdj7JnW6GRAhMC0W/Tq0lBvh2HpcWZpLY3R4fvwygw5soTZ32/pyatqwuEyNlNmG0IQcjpGaLJ3BZxhqOAzWNjp0ltgecNx0= kaaaydi"