variable "environment" {}
variable "resource_group_name" {}
variable "location" {}
variable "virtual_network_name" {}
variable "virtual_network_address_space" {}
variable "subnet_name" {}
variable "subnet_address_space" {}
variable "public_ip_name" {}
variable "ip_allocation" {}
variable "ip_sku" {}
variable "domain_name_prefix" {}
variable "network_security_group_name" {}
